version: '3.8'

services:
  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golf_club_tournament_membership_api
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://golf-club-tournament-database.c94q42ka89g7.us-east-1.rds.amazonaws.com/golf_club
      - spring.datasource.username=admin  # Your RDS username
      - spring.datasource.password=nsIHS936DMA  # Your RDS password
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.dialect=org.hibernate.dialect.MySQL8Dialect
    command: [ "java", "-jar", "app.jar"]
