version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golf_club_tournament_membership_api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/golf_club
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.dialect=org.hibernate.dialect.MySQL8Dialect
    command: [ "java", "-jar", "app.jar"]

volumes:
  mysql_data:
